### ISSUE TITLE
*** Can't Set number eff. multiplier to "n" it needs to be 12 OR the number of energies in the MCNP INPUT file NOT the experimental file

### ISSUE THREAD

**Issue by bve5056** [rtorzilli/GeDetector-Project#10]
*** Can't Set number eff. multiplier to "n" it needs to be 12 OR the number of energies in the MCNP INPUT file NOT the experimental file

**Comment by rtorzilli** [comment]
fixed, if source card energies in MCNP out put changes this will need to be manually swapped to represent that new value
