### ISSUE TITLE
Add to the Final Text File the values of the final paremeters

### ISSUE THREAD

**Issue by bve5056** [rtorzilli/GeDetector-Project#9]
- Add to the text file the values of the final paremeters
It might be better to output the difference from inital to final, so it would be easier to see what the real value is, ie dead layer changed by 1 cm,
- And then maybe add the real dimesion so it would look like: newdeadlayer = Initatial real value + Delta(New value-old value).

Where old/new value are the actual numbers in MCNP and the inital real value is the actual size (ie deadlayer = 1mm initially)

**Comment by rtorzilli** [comment]
Not messing with code to do this at this point in time since it would involve somehow getting the other values in the MCNP deck and the point is to be generic not explicit.
